### ISSUE TITLE
Research AWS Identity and Access Management (IAM) so that we can provide access to other groups as necessary

### ISSUE THREAD

**Issue by ptstory** [ptstory/EmojiChecker-Backend#12]

**Comment by hbhatt687** [comment]
We can create IAM credentials for groups. This will be easier to do instead of providing credentials to individuals, instead, we can provide relevant permissions to groups based on their job functions (administrative, front-end). 
https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html
