### ISSUE TITLE
Launch and configure RDS instance to host MySQL database

### ISSUE THREAD

**Issue by ptstory** [ptstory/EmojiChecker-Backend#13]

**Comment by LemonNa** [comment]
I'm researching on this issue currently

**Comment by hbhatt687** [comment]
We have the RDS instance running and we are able to connect to it with services such as MySQL workbench. 

![image.png](https://images.zenhubusercontent.com/5b91a84de008eb0aea5fe520/6e14b538-0c45-42f8-9ed3-d9ae0952f1d1)
