### ISSUE TITLE
Research Django framework to be ran on EC2 server

### ISSUE THREAD

**Issue by ptstory** [ptstory/EmojiChecker-Backend#15]

**Comment by hbhatt687** [comment]
We need to be familiar with python in order to use Django. Here is a link that describes how to intialilly set up Django and it provides an example case: https://docs.djangoproject.com/en/1.11/intro/tutorial01/

**Comment by slogsdon7** [comment]
http://ec2-184-72-136-95.compute-1.amazonaws.com:8080/auth/
