### ISSUE TITLE
Test server stability for long term use

### ISSUE THREAD

**Issue by LemonNa** [ptstory/EmojiChecker-Backend#24]
Test every certain time to check if server is up(responsive)

**Comment by ptstory** [comment]
All AWS services have been running for some time now without any known issues. Moving forward we could look into the capabilities of CloudWatch free tier.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/monitoring_best_practices.html
https://aws.amazon.com/cloudwatch/pricing/
