### ISSUE TITLE
Research daemons working in the background

### ISSUE THREAD

**Issue by hbhatt687** [ptstory/EmojiChecker-Backend#7]
How to poll scheduling information from the database?

**Comment by slogsdon7** [comment]
My suggestion for the sake of quick prototyping is to start with a cronjob that runs the schedule handler every minute or two. That way we don't have to debug daemon configuration/code while working on the basic functionality.

**Comment by hbhatt687** [comment]
The main background process is going to be a cronjob that will run the schedule handler (frequency TBD) and will send out notifications to users that it is time to submit emoji responses.
