### ISSUE TITLE
Decide which database engine we want to use with RDS

### ISSUE THREAD

**Issue by ptstory** [ptstory/EmojiChecker-Backend#8]
RDS can be used with:
MySQL, PostgreSQL, MariaDB, SQL Server, Oracle, and Amazon Aurora

**Comment by hbhatt687** [comment]
It looks like we will be going with MySQL. But I'm not sure if it's free to use with RDS... https://aws.amazon.com/rds/mysql/pricing/

**Comment by williamgregoryjohnson** [comment]
Look here:
https://aws.amazon.com/rds/free/
