### ISSUE TITLE
Research Moto - testing library that can be used AWS SDK for Python

### ISSUE THREAD

**Issue by ptstory** [ptstory/EmojiChecker-Backend#9]
https://github.com/spulec/moto

**Comment by williamgregoryjohnson** [comment]
I looked at the Moto "mock boto" system. Do you understand what a decorator wrapping is in Python?

It is like in java using Integer instead of int. Integer is decorator wrapper for int.

**Comment by ptstory** [comment]
I think Sam is the group member who's most familiar with Python. I read up on decorator wrapping and the main use case I found was when you have an existing function and want to make a new function that adds some extra functionality to it (the example I saw was dealing with logging). It looks like Moto uses several decorators for mocking out different AWS services.

**Comment by hbhatt687** [comment]
We will be discussing whether or not to use this for later on. Specifically we will use this to Mock AWS services so that we do not have to use our real EC2 or RDS for testing.
